### ISSUE TITLE
Doesn't highlight on initial load

### ISSUE THREAD

**Issue by rikusen0335** [chikko80/error-lens.nvim#2]
Initially it doesn't highlighted with red background:
![スクリーンショット 2023-04-05 14 27 22](https://user-images.githubusercontent.com/19174234/229989033-0639a397-9f28-4401-8a24-6596078a820c.png)

After doing `:Lazy` it seems working:
![スクリーンショット 2023-04-05 14 27 37](https://user-images.githubusercontent.com/19174234/229989047-98c5ffc9-9d44-4a0b-beb9-8cb9ab995c3f.png)

I'm not sure if this is a problem of it's my setup or the plugin's, but I just ask/create about this issue.

**Comment by chikko80** [comment]
@rikusen0335 
Thanks for your feedback!

Please post the part of your lazy.nvim config where you install the plugin

**Comment by rikusen0335** [comment]
Thank you for your response!
Well I'm currently using AstroNvim as a base, so please take a look at: https://github.com/AstroNvim/AstroNvim/blob/main/lua/astronvim/lazy.lua
I'm gonna also paste my configs here: https://github.com/rikusen0335/.astronvim

**Comment by chikko80** [comment]
I am not familiar with AstroNvim, to be honest. I just recently switched to Nvim at all. I am currently on the NvChad Framework. I don't have any problem with loading the plugin on BufRead

Can you try to replace the 
```lua 
event = 'BufRead'
```

for 

```lua 
lazy = false
```

There is maybe a problem with the lazy loading on this Event caused by AstroNvim itself

**Comment by rikusen0335** [comment]
Thank you for quick reply :)
I also moved to nvim from vscode few days ago and still learning too 😄 

Well I tried that case, disabling lazy feature, but it wouldn't work.

**Comment by rikusen0335** [comment]
The part is, I could load error-lens plugin but it won't highlight like red background.
Maybe something about virtual stuff or configuration is wrong but I'm not sure

**Comment by chikko80** [comment]
What do you mean by "it won't highlight like red background" ?

**Comment by rikusen0335** [comment]
I mean like, looking at 2nd image in the issue description, you can see background is highlighted by red, but 1st one is not

**Comment by chikko80** [comment]
Mhm its hard to say, but it isn't a problem on NvChad or any other minimal config, therefore, I think it's related to AstroNvim. I can't do anything about it probably

**Comment by rikusen0335** [comment]
Okay, then I'd close the issue, and I'm gonna try to find what is a cause of this issue.
If I found something because of this plugin, I'll open new issue

Thank you for your supporting!
