### ISSUE TITLE
Bug for Multiple diagnostics

### ISSUE THREAD

**Issue by fotscode** [chikko80/error-lens.nvim#8]
## Issue Description

When there's multiple diagnostics the foreground color of the text isn't the proper one, it uses the foreground color of the latest diagnostic applied to the line, instead of the specified at the config file. 

Also the spacing of the diagnostic message isn't properly aligned to the width of the color highlighting.

## Screenshots
**Actual:**
![image](https://github.com/chikko80/error-lens.nvim/assets/60556553/4eecf28c-a648-450c-b2c6-fab0f5c3739b)

**Expected:**
![image](https://github.com/chikko80/error-lens.nvim/assets/60556553/a69a6e1c-1b00-48de-8fb1-f93e36c2e0d2)

## Config used
```lua
{
    enabled = true,
    auto_adjust = {
        enable = false,
        fallback_bg_color = nil, -- mandatory if enable true (e.g. #281478)
        step = 7,            -- inc: colors should be brighter/darker
        total = 30           -- steps of blender
    },
    prefix = 4,              -- distance code <-> diagnostic message
    -- default colors
    colors = {
        error_fg = "#e06c75", -- diagnostic font color
        error_bg = "#4B252C", -- diagnostic line color
        warn_fg = "#e5c07b",
        warn_bg = "#554400",
        info_fg = "#61afef",
        info_bg = "#00404b",
        hint_fg = "#c678dd",
        hint_bg = "#46285d"
    }
}
```

## Solution

I have found the problem and fixed it, I was just checking if you want this change or not, if you do I could make a **pull request** and you can merge it.

**Comment by chikko80** [comment]
@fotscode 

sure PR is very welcome, thanks!
